### ISSUE TITLE
Debugging Plugin

### ISSUE THREAD

**Issue by yepher** [onekiloparsec/QLFits#3] opened 2016-12-23 17:35 UTC
When trying your steps to debug QuickLook plugin I get the following error:

```
Message from debugger: cannot attach to process due to System Integrity Protection
Program ended with exit code: -1
```

**Comment by onekiloparsec** [comment] 2016-12-23 20:17
Thanks for checking this. Indeed, the project hasn't been updated since a while, and Apple played a lot with their security policies in the meantime. I can reproduce the problem, but I still need to find a solution.

The README file must also be updated, as it doesn't reflect correct state of the debugging process.

**Comment by onekiloparsec** [comment] 2016-12-23 20:24
I found a partial solution. When setting up your Xcode "scheme" to automatically launch `qlmanage`, you should uncheck "Debug executable":

<img width="421" alt="screen shot 2016-12-23 at 21 22 29" src="https://cloud.githubusercontent.com/assets/226224/21461886/34dfca8c-c956-11e6-9a77-6b3325c9e64d.png">

However, after that, I still don't have the QuickLook window. If I run the command manually from Terminal, I get the old error I know since too much time, and against which I could find anything:

    *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xaf03, name = 'com.apple.CFPasteboardClient'
    See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by yepher** [comment] 2016-12-23 21:23
Yea, tried the disable `Debug executable` but then can't put break points or `debug`

**Comment by onekiloparsec** [comment] 2016-12-23 21:26
Agree, I'm stuck. It seems that it is anyway related to the fact that the QuickLook server has been sandboxed since Mavericks. And there is no small window to go through... See for instance https://lists.apple.com/archives/xcode-users/2015/Mar/msg00088.html

**Comment by yepher** [comment] 2016-12-23 21:27
It is too bad there is not a wrapper QuickLook client for debugging.

**Comment by onekiloparsec** [comment] 2016-12-23 21:28
I've stopped hoping for, unfortunately. You couldn't imagine the time spent on just finding some rare piece of documentation for the development of quicklook plugins by themselves.

**Comment by yepher** [comment] 2016-12-24 17:29
I tried to edit this file `sudo vi /usr/share/sandbox/qlmanage.sb` and change `(debug deny)` to `(debug allow)` but system won't allow me to edit for some reason.

**Comment by yepher** [comment] 2016-12-24 22:20
FYI,

I've played with QuickLook plugins a lot today. I've found that the following error appears to be a red herring. Even though that message is sent to console it still renders.

```
2016-12-24 16:18:56.880 qlmanage[79253:2286721] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xaf03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2016-12-24 16:18:56.937 qlmanage[79253:2286721] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xe43b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2016-12-24 16:18:56.939 qlmanage[79253:2286721] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xe703, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

```

**Comment by onekiloparsec** [comment] 2016-12-26 10:39
Did you manage to find a complete setup with rendering and breakpoints active from within Xcode?

**Comment by yepher** [comment] 2016-12-26 13:17
I've not been able to get break points working but I can see logs in XCode. I have been able to debug and set break points in [Hopper](https://www.hopperapp.com/) but this is **far** less than ideal. But I am using Hopper to see if I can get a much better understanding of how QuickLook works internally but it is very tedious.

To run in debugger I had to turn off SIP in OSX. [This](http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html) is how I did it:

1. Restart your Mac.
1. Before OS X starts up, hold down Command-R and keep it held down until you see an Apple icon and a progress bar. Release. This boots you into Recovery.
1. From the Utilities menu, select Terminal.
1. At the prompt type exactly the following and then press Return: csrutil disable
1. Terminal should display a message that SIP was disabled.
1. From the  menu, select Restart.

You can re-enable SIP by following the above steps, but using csrutil enable instead.

**Comment by yepher** [comment] 2017-01-05 22:21
I've been talking to the folks at Apple and they confirm that for now we need to disable SIP in order to debug QuickLook plugins. I'll file a bug with them but that won't help in the short term. Here is the response for your reference:

```
Xcode is not allowing qlmanage tool to run in this mode, or qlmanage tool is not configured to work with Xcode in that way.  This is a bug in the qlmanage tool, you should not have to disable SIP (System Integrity Protection) to debug your quicklook generator plugin like that.

As a workaround you can disable SIP when debugging.  Go to this article on how to do that -

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html

Obviously that’s less than ideal.  It seems to me that either the system or Xcode should provide a better way of dealing with this (either by the system modernizing the qlmanage tool or by Xcode providing some sort of direct support for debugging quicklook plugins).  Please file a bug at “http://bugreporter.apple.com” outlining the issue.

PLEASE: make sure you turn SIP back on when you are finished debugging!

In Xcode 8 you set your plugin debug target’s executable to qlmanage.  Do the following -

1) select the debug target
2) select “Edit Scheme…” in the project window’s toolbar
3) select 'Run' from the list on the left
-> the Info tab of the display on the right
4) choose “Other…” from the Executable popup. A standard file sheet will appear.
5) Type cmd-shift-g. A 'Go to folder' sheet appears with a text field.
6) Enter /usr/bin/ and hit the Go button.
-> The standard file sheet should now be showing the contents of /usr/bin.
7) Select and open the 'qlmanage' binary
8) Turn on the 'Debug executable' checkbox and click the Choose button.

Setting the executable arguments, do the following -

To use the qlmanage executable on a test document, please edit the arguments to point to the file you want to preview -

1) Select the “Arguments” tab in the Run scheme Edit sheet.
2) Add “-p ~/Desktop/” as the first argument. This is a path to a file that should already exist. Your plugin will be asked to render previews of this file.
3) Add “-c as the second argument to be passed on launch. You may need to change this depending on the kind of UTIs your plugin supports.
4) Add "-g $(CONFIGURATION_BUILD_DIR)/<your plugin name>.qlgenerator" as the second argument. This resolves to a path to the debug version of your plugin.
5) Close the Schemes sheet.

You can also test your Quick Look plug in from Terminal by using this as an example:

qlmanage -g .qlgenerator -p -c

Sometimes, you may need to manually kill off the quicklook daemon to get it to reload a new version of your plugin.
You can do so via the following in Terminal:

	killall quicklookd

To package your quicklook generator plugin with your app, just build it as a dependency target in your main project, include that plug in part of the install package, and the plugin should be installed in either /Library/QuickLook or ~/Library/Quicklook, depending on if you want the plugin to be used across multiple users or for just one specific user.

```

Not much there that we did not already know but it is good to have the confirmation.

**Comment by onekiloparsec** [comment] 2017-01-06 10:01
Thanks a lot for sharing all of this, I appreciate very much. I'll close the issue for now, but this will remain definitely a key source of info for that kind of problems.

**Closed by onekiloparsec** 2017-01-06 10:01 UTC
